# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: "0 22 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: merge
      run: |
        rm ./Complete.conf
        cat ./merge.py
        wget https://cdn.jsdelivr.net/gh/lhie1/Rules/Shadowrocket/Complete.conf
        python ./merge.py
    - name: commit
      run: |
        git config --global user.email xiangjianjian@aliyun.com
        git config --global user.name Chien
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
